version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
executors:
  standard-executor:
    machine:
      image: ubuntu-2204:current

jobs:
  sonarcloudanalyze:
    docker:
      - image: node:18
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            NPM_TOKEN=$FURY_AUTH yarn install
      - run:
          name: Run lint
          command: |
            NPM_TOKEN=$FURY_AUTH yarn lint
      - sonarcloud/scan

  pack_and_push_tag:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Detect Version Number
          command: |
            echo $CIRCLE_TAG$CIRCLE_BRANCH | cut -d/ -f2 > DYNAMIC_VERSION
            echo DYNAMIC_VERSION
      - run :
          name: Install Dependencies
          command: |
            NPM_TOKEN=$FURY_AUTH yarn install
      - run :
          name: Build package
          command: |
            sed -i -e "s!DYNAMIC_VERSION!$(cat DYNAMIC_VERSION)!" package.json
            cat package.json
            mkdir -p packages
            NPM_TOKEN=$FURY_AUTH yarn build
            NPM_TOKEN=$FURY_AUTH yarn pack -o packages/syngenta-digital-planting-common-ops.tgz
      - run :
          name: Publish package
          command: |
            echo Publishing version $(cat DYNAMIC_VERSION)
            curl -ivF 'package=@packages/syngenta-digital-planting-common-ops.tgz' "https://${FURY_PUSH_TOKEN}@push.fury.io/syngenta-digital/"
      - store_artifacts:
          name: "Save the built package."
          path: ./packages/
          when: always

workflows:
  version: 2.1
  Code quality:
    jobs:
      - sonarcloudanalyze:
          context:
            - cropwise-seed-cicd
            - shared-sonarcloud-token
            - shared-gemfury-tokens
          filters:
            tags:
              only:
                - /.*/
            branches:
              only:
                - /.*/
  

  pack_and_push_tag:
    jobs:
      - pack_and_push_tag:
          context:
            - cropwise-seed-cicd
            - shared-sonarcloud-token
            - shared-gemfury-tokens
          filters:
            branches:
              only:
                - /ci\/.*/
            tags:
              only:
                - /release\/.*/

